name: Update Random Number

on:
  schedule:
    - cron: "50 21 * * *"  # Runs at 21:50 UTC
  workflow_dispatch:  # Allows manual trigger

jobs:
  update-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate random number
        run: |
          echo '{"date": "'$(TZ="UTC" date -d "tomorrow" +"%Y-%m-%d")'", "number": '$(shuf -i 0-115 -n 1)'}' > random_number.json

      - name: Commit and push
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add random_number.json
          git commit -m "Updated random number"
          git push origin main
